codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

coverage:
  status:
    project:
      default:   # default is the status check's name, not default settings
        target: 100%
        threshold: 1%
        if_ci_failed: success #success, failure, error, ignore
        informational: true
        only_pulls: false
    patch:
      default:
        informational: true
  parsers:
    javascript:
      enable_partials: yes

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: false     # [yes :: must have a base report to post]
  require_head: false      # [yes :: must have a head report to post]
