codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
  status:
    project:
      default:
        target: 100%
        threshold: 1%
        informational: true
    patch:
      default:
        informational: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: false     # [yes :: must have a base report to post]
  require_head: false      # [yes :: must have a head report to post]

coverage:
  parsers:
    javascript:
      enable_partials: yes
