<?php

return [
    'issue-343' => [
        'ua' => 'Mozilla/5.0 (PlayStation 4 1.72) AppleWebKit/536.26 (KHTML, like Gecko)',
        'properties' => [
            'Comment' => 'Playstation Browser',
            'Browser' => 'Playstation Browser',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Sony',
            'Browser_Modus' => 'unknown',
            'Version' => '0.0',
            'Platform' => 'OrbisOS',
            'Platform_Version' => 'unknown',
            'Platform_Description' => 'unknown',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Sony',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => true,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'Playstation 4',
            'Device_Maker' => 'Sony',
            'Device_Type' => 'TV Device',
            'Device_Pointing_Method' => 'mouse',
            'Device_Code_Name' => 'PS4',
            'Device_Brand_Name' => 'Sony',
            'RenderingEngine_Name' => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Apple Inc',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
];
