<?php

declare(strict_types=1);

return [
    'issue-1998-A' => [
        'ua' => 'Mozilla/5.0 (Android 8.0.0; SM-G950F Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.9 YaaniBrowser/4.2.0.186 (Turkcell-TR) Mobile Safari/537.36',
        'properties' => [
            'Comment' => 'YaaniBrowser 4.2',
            'Browser' => 'YaaniBrowser',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Turkcell',
            'Browser_Modus' => 'unknown',
            'Version' => '4.2',
            'Platform' => 'Android',
            'Platform_Version' => '8.0',
            'Platform_Description' => 'Android OS',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Google Inc',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => false,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'Galaxy S8 (Global)',
            'Device_Maker' => 'Samsung',
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'SM-G950F',
            'Device_Brand_Name' => 'Samsung',
            'RenderingEngine_Name' => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Google Inc',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
    'issue-1998-B' => [
        'ua' => 'Booking.com Android App 16.0.0.5723278 (OS: 8.1.0; Type: tablet; AppStore: google; Brand: samsung; Model: SM-T590;)',
        'properties' => [
            'Comment' => 'Booking.com App',
            'Browser' => 'Booking.com App',
            'Browser_Type' => 'Application',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Booking.com',
            'Browser_Modus' => 'unknown',
            'Version' => '0.0',
            'Platform' => 'Android',
            'Platform_Version' => '8.1',
            'Platform_Description' => 'Android OS',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Google Inc',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => false,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'Galaxy Tab A (10.5, Wi-Fi)',
            'Device_Maker' => 'Samsung',
            'Device_Type' => 'Tablet',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'SM-T590',
            'Device_Brand_Name' => 'Samsung',
            'RenderingEngine_Name' => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Google Inc',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
];
