<?php

declare(strict_types=1);

return [
    'issue-2111-A' => [
        'ua' => 'Mozilla/5.0 (Linux; U; Android 9; zh-cn; GM1910 Build/PKQ1.190110.001) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.134 Mobile Safari/537.36 OnePlusBrowser/30.5.0.8',
        'properties' => [
            'Comment' => 'OnePlus Browser 30.5',
            'Browser' => 'OnePlus Browser',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'unknown',
            'Browser_Modus' => 'unknown',
            'Version' => '30.5',
            'Platform' => 'Android',
            'Platform_Version' => '9.0',
            'Platform_Description' => 'Android OS',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Google Inc',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => false,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => '7 Pro',
            'Device_Maker' => 'OnePlus',
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'GM1910',
            'Device_Brand_Name' => 'OnePlus',
            'RenderingEngine_Name' => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Google Inc',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
];
