<?php

return [
    'issue-723' => [
        'ua' => 'Mozilla/5.0 (X11; Linux x86_64; Ubuntu 14.04.2 LTS) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.0 Maxthon/1.0.5.3 Safari/537.36',
        'properties' => [
            'Comment' => 'Maxthon 1.0 for Linux',
            'Browser' => 'Maxthon',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '64',
            'Browser_Maker' => 'Maxthon International Limited',
            'Browser_Modus' => 'unknown',
            'Version' => '1.0',
            'Platform' => 'Ubuntu',
            'Platform_Version' => '14.04',
            'Platform_Description' => 'Ubuntu Linux',
            'Platform_Bits' => '64',
            'Platform_Maker' => 'Canonical Foundation',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => false,
            'isSyndicationReader' => false,
            'Crawler' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'Linux Desktop',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
            'Device_Code_Name' => 'Linux Desktop',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Google Inc',
        ],
        'lite' => false,
        'standard' => false,
        'full' => true,
    ],
    'issue-723 (standard)' => [
        'ua' => 'Mozilla/5.0 (X11; Linux x86_64; Ubuntu 14.04.2 LTS) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.0 Maxthon/1.0.5.3 Safari/537.36',
        'properties' => [
            'Comment' => 'Maxthon 1.0 for Linux',
            'Browser' => 'Maxthon',
            'Browser_Maker' => 'Maxthon International Limited',
            'Version' => '1.0',
            'Platform' => 'Linux',
            'Crawler' => false,
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
        ],
        'lite' => false,
        'standard' => true,
        'full' => false,
    ],
    'issue-723 (lite)' => [
        'ua' => 'Mozilla/5.0 (X11; Linux x86_64; Ubuntu 14.04.2 LTS) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.0 Maxthon/1.0.5.3 Safari/537.36',
        'properties' => [
            'Comment' => 'Chrome Generic',
            'Browser' => 'Chrome',
            'Version' => '0.0',
            'Platform' => 'Linux',
            'Device_Type' => 'Desktop',
        ],
        'lite' => true,
        'standard' => false,
        'full' => false,
    ],
];
