<?php

declare(strict_types=1);

return [
    'issue-2032-A' => [
        'ua' => 'TwitterAndroid/7.71.1-release.15 (8900196-r-15) TA-1028/8.0.0 (HMD Global;TA-1028;Nokia;TA-1028_00WW;0;;1;2013)',
        'properties' => [
            'Comment' => 'Twitter App',
            'Browser' => 'Twitter App',
            'Browser_Type' => 'Application',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Twitter',
            'Browser_Modus' => 'unknown',
            'Version' => '0.0',
            'Platform' => 'Android',
            'Platform_Version' => 'unknown',
            'Platform_Description' => 'Android OS',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Google Inc',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => false,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => '3',
            'Device_Maker' => 'Nokia',
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'TA-1028',
            'Device_Brand_Name' => 'Nokia',
            'RenderingEngine_Name' => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Google Inc',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
];
