<?php

declare(strict_types=1);

return [
    'issue-269-A' => [
        'ua' => 'Slackbot-LinkExpanding (+https://api.slack.com/robots)',
        'properties' => [
            'Comment' => 'Social Bookmarkers',
            'Browser' => 'Slackbot-Link-Expanding',
            'Browser_Type' => 'Bot/Crawler',
            'Browser_Bits' => '0',
            'Browser_Maker' => 'slack.com',
            'Browser_Modus' => 'unknown',
            'Version' => '0.0',
            'Platform' => 'unknown',
            'Platform_Version' => 'unknown',
            'Platform_Description' => 'unknown',
            'Platform_Bits' => '0',
            'Platform_Maker' => 'unknown',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => false,
            'IFrames' => false,
            'Tables' => false,
            'Cookies' => false,
            'JavaScript' => false,
            'VBScript' => false,
            'JavaApplets' => false,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '0',
            'Device_Name' => 'unknown',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'unknown',
            'Device_Pointing_Method' => 'unknown',
            'Device_Code_Name' => 'unknown',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'unknown',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
    'issue-269-B' => [
        'ua' => 'Slackbot (+https://api.slack.com/robots)',
        'properties' => [
            'Comment' => 'Social Bookmarkers',
            'Browser' => 'Slackbot',
            'Browser_Type' => 'Bot/Crawler',
            'Browser_Bits' => '0',
            'Browser_Maker' => 'slack.com',
            'Browser_Modus' => 'unknown',
            'Version' => '0.0',
            'Platform' => 'unknown',
            'Platform_Version' => 'unknown',
            'Platform_Description' => 'unknown',
            'Platform_Bits' => '0',
            'Platform_Maker' => 'unknown',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => false,
            'IFrames' => false,
            'Tables' => false,
            'Cookies' => false,
            'JavaScript' => false,
            'VBScript' => false,
            'JavaApplets' => false,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '0',
            'Device_Name' => 'unknown',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'unknown',
            'Device_Pointing_Method' => 'unknown',
            'Device_Code_Name' => 'unknown',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'unknown',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
];
