<?php

declare(strict_types=1);

return [
    'issue-995' => [
        'ua' => 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/8.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)',
        'properties' => [
            'Comment' => 'IE 11.0 in IE 7.0 Compatibility Mode',
            'Browser' => 'IE',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Microsoft Corporation',
            'Browser_Modus' => 'IE 7.0 Compatibility Mode',
            'Version' => '11.0',
            'Platform' => 'Win10',
            'Platform_Version' => '10.0',
            'Platform_Description' => 'Windows 10',
            'Platform_Bits' => '64',
            'Platform_Maker' => 'Microsoft Corporation',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => true,
            'JavaApplets' => true,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'Windows Desktop',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
            'Device_Code_Name' => 'Windows Desktop',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'Trident',
            'RenderingEngine_Version' => '8.0',
            'RenderingEngine_Maker' => 'Microsoft Corporation',
        ],
        'lite' => true,
        'standard' => true,
        'full' => true,
    ],
];
