<?php

return [
    'issue-146' => [
        'ua' => 'Mozilla/4.0 (compatible; MSIE 7.0;Windows NT 5.1;.NET CLR 1.1.4322;.NET CLR 2.0.50727;.NET CLR 3.0.04506.30) Lightspeedsystems',
        'properties' => [
            'Comment' => 'Lightspeed Systems RocketCrawler',
            'Browser' => 'Lightspeed Systems Crawler',
            'Browser_Type' => 'Bot/Crawler',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Lightspeed Systems',
            'Browser_Modus' => 'unknown',
            'Version' => '0.0',
            'Platform' => 'WinXP',
            'Platform_Version' => '5.1',
            'Platform_Description' => 'Windows XP',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Microsoft Corporation',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => false,
            'IFrames' => false,
            'Tables' => false,
            'Cookies' => false,
            'JavaScript' => false,
            'VBScript' => false,
            'JavaApplets' => false,
            'isSyndicationReader' => false,
            'Crawler' => true,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '0',
            'Device_Name' => 'Windows Desktop',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
            'Device_Code_Name' => 'Windows Desktop',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'unknown',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
    'issue-146 (lite)' => [
        'ua' => 'Mozilla/4.0 (compatible; MSIE 7.0;Windows NT 5.1;.NET CLR 1.1.4322;.NET CLR 2.0.50727;.NET CLR 3.0.04506.30) Lightspeedsystems',
        'properties' => [
            'Comment' => 'IE 7.0',
            'Browser' => 'IE',
            'Version' => '7.0',
            'Platform' => 'unknown',
            'Device_Type' => 'Desktop',
        ],
        'lite' => true,
        'standard' => false,
        'full' => false,
    ],
];
