<?php

return [
    'issue-2130-A' => [
        'ua' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.7822.1481 Safari/537.36; Bytespider',
        'properties' => [
            'Comment' => 'Chrome 43.0',
            'Browser' => 'Chrome',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Google Inc',
            'Browser_Modus' => 'unknown',
            'Version' => '43.0',
            'Platform' => 'macOS',
            'Platform_Version' => '10.14',
            'Platform_Description' => 'macOS',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Apple Inc',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => false,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'Macintosh',
            'Device_Maker' => 'Apple Inc',
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
            'Device_Code_Name' => 'Macintosh',
            'Device_Brand_Name' => 'Apple',
            'RenderingEngine_Name' => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Google Inc',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
    'issue-2130-A (lite)' => [
        'ua' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.7822.1481 Safari/537.36; Bytespider',
        'properties' => [
            'Comment' => 'Chrome Generic',
            'Browser' => 'Chrome',
            'Version' => '0.0',
            'Platform' => 'MacOSX',
            'Device_Type' => 'Desktop',
        ],
        'lite' => true,
        'standard' => false,
        'full' => false,
    ],
    'issue-2130-B' => [
        'ua' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36 (compatible; Centricbot/1.0; centricbot@centricdigital.com)',
        'properties' => [
            'Comment' => 'Chrome 74.0',
            'Browser' => 'Chrome',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Google Inc',
            'Browser_Modus' => 'unknown',
            'Version' => '74.0',
            'Platform' => 'macOS',
            'Platform_Version' => '10.14',
            'Platform_Description' => 'macOS',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Apple Inc',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => false,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'Macintosh',
            'Device_Maker' => 'Apple Inc',
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
            'Device_Code_Name' => 'Macintosh',
            'Device_Brand_Name' => 'Apple',
            'RenderingEngine_Name' => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Google Inc',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
    'issue-2130-B (lite)' => [
        'ua' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36 (compatible; Centricbot/1.0; centricbot@centricdigital.com)',
        'properties' => [
            'Comment' => 'Chrome 74.0',
            'Browser' => 'Chrome',
            'Version' => '74.0',
            'Platform' => 'MacOSX',
            'Device_Type' => 'Desktop',
        ],
        'lite' => true,
        'standard' => false,
        'full' => false,
    ],
    'issue-2130-C' => [
        'ua' => 'AdsTxtCrawler/1.0; +https://github.com/InteractiveAdvertisingBureau/adstxtcrawler',
        'properties' => [
            'Comment' => 'Chrome 74.0',
            'Browser' => 'Chrome',
            'Version' => '74.0',
            'Platform' => 'MacOSX',
            'Device_Type' => 'Desktop',
        ],
        'lite' => true,
        'standard' => false,
        'full' => false,
    ],
    'issue-2130-D' => [
        'ua' => 'Alignabot 1.0 (https://www.alignable.com/)',
        'properties' => [
            'Comment' => 'Chrome 74.0',
            'Browser' => 'Chrome',
            'Version' => '74.0',
            'Platform' => 'MacOSX',
            'Device_Type' => 'Desktop',
        ],
        'lite' => true,
        'standard' => false,
        'full' => false,
    ],
    'issue-2130-E' => [
        'ua' => 'Autn-WKOOP',
        'properties' => [
            'Comment' => 'Chrome 74.0',
            'Browser' => 'Chrome',
            'Version' => '74.0',
            'Platform' => 'MacOSX',
            'Device_Type' => 'Desktop',
        ],
        'lite' => true,
        'standard' => false,
        'full' => false,
    ],
    'issue-2130-F' => [
        'ua' => 'IVW-Crawler-6476133',
        'properties' => [
            'Comment' => 'Chrome 74.0',
            'Browser' => 'Chrome',
            'Version' => '74.0',
            'Platform' => 'MacOSX',
            'Device_Type' => 'Desktop',
        ],
        'lite' => true,
        'standard' => false,
        'full' => false,
    ],
    'issue-2130-G' => [
        'ua' => 'Mozilla/5.0 (compatible; 2GDPR/1.2; https://2gdpr.com)',
        'properties' => [
            'Comment' => 'Chrome 74.0',
            'Browser' => 'Chrome',
            'Version' => '74.0',
            'Platform' => 'MacOSX',
            'Device_Type' => 'Desktop',
        ],
        'lite' => true,
        'standard' => false,
        'full' => false,
    ],
    'issue-2130-H' => [
        'ua' => 'Mozilla/5.0 (compatible; OnCrawl/1.0; +http://www.oncrawl.com)',
        'properties' => [
            'Comment' => 'Chrome 74.0',
            'Browser' => 'Chrome',
            'Version' => '74.0',
            'Platform' => 'MacOSX',
            'Device_Type' => 'Desktop',
        ],
        'lite' => true,
        'standard' => false,
        'full' => false,
    ],
    'issue-2130-I' => [
        'ua' => 'Mozilla/5.0 (compatible; OpenindexSpider; +https://www.openindex.io/saas/about-our-spider/)',
        'properties' => [
            'Comment' => 'Chrome 74.0',
            'Browser' => 'Chrome',
            'Version' => '74.0',
            'Platform' => 'MacOSX',
            'Device_Type' => 'Desktop',
        ],
        'lite' => true,
        'standard' => false,
        'full' => false,
    ],
    'issue-2130-J' => [
        'ua' => 'Mozilla/5.0 (compatible; Pinterestbot/1.0; +http://www.pinterest.com/bot.html)',
        'properties' => [
            'Comment' => 'Chrome 74.0',
            'Browser' => 'Chrome',
            'Version' => '74.0',
            'Platform' => 'MacOSX',
            'Device_Type' => 'Desktop',
        ],
        'lite' => true,
        'standard' => false,
        'full' => false,
    ],
    'issue-2130-K' => [
        'ua' => 'Mozilla/5.0 (compatible; iSec_v2_Bot/1.0;)',
        'properties' => [
            'Comment' => 'Chrome 74.0',
            'Browser' => 'Chrome',
            'Version' => '74.0',
            'Platform' => 'MacOSX',
            'Device_Type' => 'Desktop',
        ],
        'lite' => true,
        'standard' => false,
        'full' => false,
    ],
    'issue-2130-L' => [
        'ua' => 'Mozilla/5.0 (compatible; woorankreview/2.0; +https://www.woorank.com/)',
        'properties' => [
            'Comment' => 'Chrome 74.0',
            'Browser' => 'Chrome',
            'Version' => '74.0',
            'Platform' => 'MacOSX',
            'Device_Type' => 'Desktop',
        ],
        'lite' => true,
        'standard' => false,
        'full' => false,
    ],
    'issue-2130-M' => [
        'ua' => 'Snap/1.0 (+https://www.diffbot.com/dev/docs/crawl/)',
        'properties' => [
            'Comment' => 'Chrome 74.0',
            'Browser' => 'Chrome',
            'Version' => '74.0',
            'Platform' => 'MacOSX',
            'Device_Type' => 'Desktop',
        ],
        'lite' => true,
        'standard' => false,
        'full' => false,
    ],
    'issue-2130-N' => [
        'ua' => 'Squirrly crawler2',
        'properties' => [
            'Comment' => 'Chrome 74.0',
            'Browser' => 'Chrome',
            'Version' => '74.0',
            'Platform' => 'MacOSX',
            'Device_Type' => 'Desktop',
        ],
        'lite' => true,
        'standard' => false,
        'full' => false,
    ],
    'issue-2130-O' => [
        'ua' => 'pyspider/0.3.10 (+http://pyspider.org/)',
        'properties' => [
            'Comment' => 'Chrome 74.0',
            'Browser' => 'Chrome',
            'Version' => '74.0',
            'Platform' => 'MacOSX',
            'Device_Type' => 'Desktop',
        ],
        'lite' => true,
        'standard' => false,
        'full' => false,
    ],
];
