<?php

return [
    'issue-975' => [
        'ua' => 'Dalvik/2.1.0 (Linux; U; Android 6.0.1; MI 4LTE MIUI/V7.3.2.0.MXDCNDD) NewsArticle/5.1.3',
        'properties' => [
            'Comment' => 'NewsArticle App',
            'Browser' => 'NewsArticle App',
            'Browser_Type' => 'Application',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'unknown',
            'Browser_Modus' => 'unknown',
            'Version' => '0.0',
            'Platform' => 'Miui OS',
            'Platform_Version' => '7.3',
            'Platform_Description' => 'a fork of Android OS by Xiaomi',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Xiaomi Tech',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => true,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'Mi 4 LTE',
            'Device_Maker' => 'Xiaomi Tech',
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'Mi 4 LTE',
            'Device_Brand_Name' => 'Xiaomi',
            'RenderingEngine_Name' => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Apple Inc',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
];
