<?php

return [
    'issue-004' => [
        'ua' => 'Mozilla/5.0 (PLAYSTATION 3; 2.00)',
        'properties' => [
            'Comment' => 'Playstation Browser',
            'Browser' => 'Playstation Browser',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Sony',
            'Browser_Modus' => 'unknown',
            'Version' => '0.0',
            'Platform' => 'CellOS',
            'Platform_Version' => 'unknown',
            'Platform_Description' => 'unknown',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Sony',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => false,
            'isMobileDevice' => false,
            'isTablet' => false,
            'isSyndicationReader' => false,
            'Crawler' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '2',
            'Device_Name' => 'Playstation 3',
            'Device_Maker' => 'Sony',
            'Device_Type' => 'TV Device',
            'Device_Pointing_Method' => 'mouse',
            'Device_Code_Name' => 'PS3',
            'Device_Brand_Name' => 'Sony',
            'RenderingEngine_Name' => 'NetFront',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Access',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
];
