<?php

return [
    'issue-1647-A' => [
        'ua' => 'Apple-PubSub/65',
        'properties' => [
            'Comment' => 'Apple PubSub 65',
            'Browser' => 'Apple PubSub',
            'Browser_Type' => 'Feed Reader',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Apple Inc',
            'Browser_Modus' => 'unknown',
            'Version' => '65',
            'Platform' => 'MacOSX',
            'Platform_Version' => '10',
            'Platform_Description' => 'Mac OS X',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Apple Inc',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => false,
            'IFrames' => false,
            'Tables' => false,
            'Cookies' => false,
            'JavaScript' => false,
            'VBScript' => false,
            'JavaApplets' => true,
            'isMobileDevice' => false,
            'isTablet' => false,
            'isSyndicationReader' => true,
            'Crawler' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '0',
            'Device_Name' => 'Macintosh',
            'Device_Maker' => 'Apple Inc',
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
            'Device_Code_Name' => 'Macintosh',
            'Device_Brand_Name' => 'Apple',
            'RenderingEngine_Name' => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Apple Inc',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
];
