<?php

declare(strict_types=1);

return [
    'issue-2094-A' => [
        'ua' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:33.0) Gecko/20100101 Firefox/33.0 NETVIGIE',
        'properties' => [
            'Comment' => 'netvigie Bot',
            'Browser' => 'netvigie Bot',
            'Browser_Type' => 'Bot',
            'Browser_Bits' => '64',
            'Browser_Maker' => 'netvigie.com',
            'Browser_Modus' => 'unknown',
            'Version' => '0.0',
            'Platform' => 'Ubuntu',
            'Platform_Version' => 'unknown',
            'Platform_Description' => 'Ubuntu Linux',
            'Platform_Bits' => '64',
            'Platform_Maker' => 'Canonical Foundation',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => true,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '2',
            'Device_Name' => 'Linux Desktop',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
            'Device_Code_Name' => 'Linux Desktop',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'Gecko',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Mozilla Foundation',
        ],
        'lite' => false,
        'standard' => false,
        'full' => true,
    ],
    'issue-2094-A (standard)' => [
        'ua' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:33.0) Gecko/20100101 Firefox/33.0 NETVIGIE',
        'properties' => [
            'Comment' => 'netvigie Bot',
            'Browser' => 'netvigie Bot',
            'Browser_Maker' => 'netvigie.com',
            'Version' => '0.0',
            'Platform' => 'Linux',
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
        ],
        'lite' => false,
        'standard' => true,
        'full' => false,
    ],
];
