<?php

declare(strict_types=1);

return [
    'issue-689-A' => [
        'ua' => 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Thunderbird/38.0.1 Lightning/4.0.0.1',
        'properties' => [
            'Comment' => 'Thunderbird 38.0',
            'Browser' => 'Thunderbird',
            'Browser_Type' => 'Email Client',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Mozilla Foundation',
            'Browser_Modus' => 'unknown',
            'Version' => '38.0',
            'Platform' => 'Win7',
            'Platform_Version' => '6.1',
            'Platform_Description' => 'Windows 7',
            'Platform_Bits' => '64',
            'Platform_Maker' => 'Microsoft Corporation',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => true,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'Windows Desktop',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
            'Device_Code_Name' => 'Windows Desktop',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'Gecko',
            'RenderingEngine_Version' => '38.0',
            'RenderingEngine_Maker' => 'Mozilla Foundation',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
    'issue-689-B' => [
        'ua' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Thunderbird/38.0.1 Lightning/4.0.0.1',
        'properties' => [
            'Comment' => 'Thunderbird 38.0',
            'Browser' => 'Thunderbird',
            'Browser_Type' => 'Email Client',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Mozilla Foundation',
            'Browser_Modus' => 'unknown',
            'Version' => '38.0',
            'Platform' => 'MacOSX',
            'Platform_Version' => '10.10',
            'Platform_Description' => 'Mac OS X',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Apple Inc',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => true,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'Macintosh',
            'Device_Maker' => 'Apple Inc',
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
            'Device_Code_Name' => 'Macintosh',
            'Device_Brand_Name' => 'Apple',
            'RenderingEngine_Name' => 'Gecko',
            'RenderingEngine_Version' => '38.0',
            'RenderingEngine_Maker' => 'Mozilla Foundation',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
];
