<?php

return [
    'issue-1365-A' => [
        'ua' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) FxiOS/7.0b2330 Mobile/14D27 Safari/602.4.6',
        'properties' => [
            'Comment' => 'Firefox 7.0 for iOS',
            'Browser' => 'Firefox for iOS',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Mozilla Foundation',
            'Browser_Modus' => 'unknown',
            'Version' => '7.0',
            'Platform' => 'iOS',
            'Platform_Version' => '10.2',
            'Platform_Description' => 'iPod, iPhone & iPad',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Apple Inc',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => true,
            'isSyndicationReader' => false,
            'Crawler' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'iPhone',
            'Device_Maker' => 'Apple Inc',
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'iPhone',
            'Device_Brand_Name' => 'Apple',
            'RenderingEngine_Name' => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Apple Inc',
        ],
        'lite' => false,
        'standard' => false,
        'full' => true,
    ],
    'issue-1365-A (standard)' => [
        'ua' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) FxiOS/7.0b2330 Mobile/14D27 Safari/602.4.6',
        'properties' => [
            'Comment' => 'Firefox 7.0 for iOS',
            'Browser' => 'Firefox for iOS',
            'Browser_Maker' => 'Mozilla Foundation',
            'Version' => '7.0',
            'Platform' => 'iOS',
            'Crawler' => false,
            'Device_Type' => 'Mobile Device',
            'Device_Pointing_Method' => 'touchscreen',
        ],
        'lite' => false,
        'standard' => true,
        'full' => false,
    ],
    'issue-1365-B' => [
        'ua' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) FxiOS/7.1b2565 Mobile/14E304 Safari/603.1.30',
        'properties' => [
            'Comment' => 'Firefox 7.1 for iOS',
            'Browser' => 'Firefox for iOS',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Mozilla Foundation',
            'Browser_Modus' => 'unknown',
            'Version' => '7.1',
            'Platform' => 'iOS',
            'Platform_Version' => '10.3',
            'Platform_Description' => 'iPod, iPhone & iPad',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Apple Inc',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => true,
            'isSyndicationReader' => false,
            'Crawler' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'iPhone',
            'Device_Maker' => 'Apple Inc',
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'iPhone',
            'Device_Brand_Name' => 'Apple',
            'RenderingEngine_Name' => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Apple Inc',
        ],
        'lite' => false,
        'standard' => false,
        'full' => true,
    ],
    'issue-1365-B (standard)' => [
        'ua' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) FxiOS/7.1b2565 Mobile/14E304 Safari/603.1.30',
        'properties' => [
            'Comment' => 'Firefox 7.1 for iOS',
            'Browser' => 'Firefox for iOS',
            'Browser_Maker' => 'Mozilla Foundation',
            'Version' => '7.1',
            'Platform' => 'iOS',
            'Crawler' => false,
            'Device_Type' => 'Mobile Device',
            'Device_Pointing_Method' => 'touchscreen',
        ],
        'lite' => false,
        'standard' => true,
        'full' => false,
    ],
];
