<?php

return [
    'issue-1428-A' => [
        'ua' => 'LG-GS290/V100 Obigo/WAP2.0 Profile/MIDP-2.1 Configuration/CLDC-1.1',
        'properties' => [
            'Comment' => 'Teleca-Obigo',
            'Browser' => 'Teleca-Obigo',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Obigo',
            'Browser_Modus' => 'unknown',
            'Version' => '0.0',
            'MajorVer' => '0',
            'MinorVer' => '0',
            'Platform' => 'JAVA',
            'Platform_Version' => 'unknown',
            'Platform_Description' => 'unknown',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Oracle',
            'Alpha' => false,
            'Beta' => false,
            'Win16' => false,
            'Win32' => false,
            'Win64' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'BackgroundSounds' => false,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => false,
            'ActiveXControls' => false,
            'isMobileDevice' => true,
            'isTablet' => false,
            'isSyndicationReader' => false,
            'Crawler' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '1',
            'AolVersion' => '0',
            'Device_Name' => 'Cookie Fresh',
            'Device_Maker' => 'LG',
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'GS290',
            'Device_Brand_Name' => 'LG',
            'RenderingEngine_Name' => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'unknown',
        ],
        'lite' => false,
        'standard' => false,
        'full' => true,
    ],
    'issue-1428-A (standard)' => [
        'ua' => 'LG-GS290/V100 Obigo/WAP2.0 Profile/MIDP-2.1 Configuration/CLDC-1.1',
        'properties' => [
            'Comment' => 'Teleca-Obigo',
            'Browser' => 'Teleca-Obigo',
            'Browser_Maker' => 'Obigo',
            'Version' => '0.0',
            'MajorVer' => '0',
            'MinorVer' => '0',
            'Platform' => 'JAVA',
            'isMobileDevice' => true,
            'isTablet' => false,
            'Crawler' => false,
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'unknown',
        ],
        'lite' => false,
        'standard' => true,
        'full' => false,
    ],
];
