<?php

declare(strict_types=1);

return [
    'issue-487' => [
        'ua' => 'Mozilla/5.0 (X11; U; Linux x86_64; zh-TW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.114 Safari/537.36 Puffin/3.7.0IT',
        'properties' => [
            'Comment' => 'Puffin 3.7',
            'Browser' => 'Puffin',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'CloudMosa Inc.',
            'Browser_Modus' => 'unknown',
            'Version' => '3.7',
            'Platform' => 'iOS',
            'Platform_Version' => 'unknown',
            'Platform_Description' => 'iPod, iPhone & iPad',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Apple Inc',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => true,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'iPad',
            'Device_Maker' => 'Apple Inc',
            'Device_Type' => 'Tablet',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'iPad',
            'Device_Brand_Name' => 'Apple',
            'RenderingEngine_Name' => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Apple Inc',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
];
