<?php

return [
    'issue-382' => [
        'ua' => 'iOS/6.1.3 (10B329) dataaccessd/1.0',
        'properties' => [
            'Comment' => 'iOS dataaccessd',
            'Browser' => 'iOS dataaccessd',
            'Browser_Type' => 'Application',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Apple Inc',
            'Browser_Modus' => 'unknown',
            'Version' => '1.0',
            'MajorVer' => '1',
            'MinorVer' => '0',
            'Platform' => 'iOS',
            'Platform_Version' => '6.1',
            'Platform_Description' => 'iPod, iPhone & iPad',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Apple Inc',
            'Alpha' => false,
            'Beta' => false,
            'Win16' => false,
            'Win32' => false,
            'Win64' => false,
            'Frames' => false,
            'IFrames' => false,
            'Tables' => false,
            'Cookies' => false,
            'BackgroundSounds' => false,
            'JavaScript' => false,
            'VBScript' => false,
            'JavaApplets' => true,
            'ActiveXControls' => false,
            'isMobileDevice' => true,
            'isTablet' => false,
            'isSyndicationReader' => false,
            'Crawler' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '0',
            'AolVersion' => '0',
            'Device_Name' => 'general Mobile Device',
            'Device_Maker' => 'Apple Inc',
            'Device_Type' => 'Mobile Device',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'general Mobile Device',
            'Device_Brand_Name' => 'Apple',
            'RenderingEngine_Name' => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Apple Inc',
        ],
        'lite' => false,
        'standard' => true,
    ],
];
