<?php

return [
    'issue-266' => [
        'ua' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:32.0) Gecko/20100101 Firefox/32.0',
        'properties' => [
            'Comment' => 'Firefox 32.0',
            'Browser' => 'Firefox',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '64',
            'Browser_Maker' => 'Mozilla Foundation',
            'Browser_Modus' => 'unknown',
            'Version' => '32.0',
            'Platform' => 'Ubuntu',
            'Platform_Version' => 'unknown',
            'Platform_Description' => 'Ubuntu Linux',
            'Platform_Bits' => '64',
            'Platform_Maker' => 'Canonical Foundation',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => true,
            'isSyndicationReader' => false,
            'Crawler' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'Linux Desktop',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
            'Device_Code_Name' => 'Linux Desktop',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'Gecko',
            'RenderingEngine_Version' => '32.0',
            'RenderingEngine_Maker' => 'Mozilla Foundation',
        ],
        'lite' => false,
        'standard' => false,
        'full' => true,
    ],
    'issue-266 (standard + lite)' => [
        'ua' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:32.0) Gecko/20100101 Firefox/32.0',
        'properties' => [
            'Comment' => 'Firefox 32.0',
            'Browser' => 'Firefox',
            'Browser_Maker' => 'Mozilla Foundation',
            'Version' => '32.0',
            'Platform' => 'Linux',
            'Crawler' => false,
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
        ],
        'lite' => true,
        'standard' => true,
        'full' => false,
    ],
];
