<?php

declare(strict_types=1);

return [
    'issue-2479-A' => [
        'ua' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Mobile/15E148 Safari/604.1',
        'properties' => [
            'Comment' => 'Mobile Safari 14.1',
            'Browser' => 'Safari',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Apple Inc',
            'Browser_Modus' => 'unknown',
            'Version' => '14.1',
            'Platform' => 'iOS',
            'Platform_Version' => '14.7',
            'Platform_Description' => 'iPod, iPhone & iPad',
            'Platform_Bits' => '64',
            'Platform_Maker' => 'Apple Inc',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => true,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => true,
            'CssVersion' => '3',
            'Device_Name' => 'iPad',
            'Device_Maker' => 'Apple Inc',
            'Device_Type' => 'Mobile Device',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'iPhone',
            'Device_Brand_Name' => 'Apple',
            'RenderingEngine_Name' => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Apple Inc',
        ],
        'lite' => false,
        'standard' => false,
        'full' => false,
    ],
];
