<?php

return [
    'issue-1442-A' => [
        'ua' => 'Mozilla/4.0 (compatible; Linux 2.6.22) NetFront/3.4 Kindle/2.0 (screen 600x800)',
        'properties' => [
            'Comment' => 'Access NetFront 3.4',
            'Browser' => 'NetFront',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '0',
            'Browser_Maker' => 'Access',
            'Browser_Modus' => 'unknown',
            'Version' => '3.4',
            'Platform' => 'unknown',
            'Platform_Version' => 'unknown',
            'Platform_Description' => 'unknown',
            'Platform_Bits' => '0',
            'Platform_Maker' => 'unknown',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => false,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '2',
            'Device_Name' => 'Kindle',
            'Device_Maker' => 'Amazon.com, Inc.',
            'Device_Type' => 'Ebook Reader',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'Kindle',
            'Device_Brand_Name' => 'Amazon',
            'RenderingEngine_Name' => 'NetFront',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Access',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
    'issue-1442-B' => [
        'ua' => 'SonyEricssonJ10i2/R7CA Browser/NetFront/3.5 Profile/MIDP-2.1 Configuration/CLDC-1.1 JavaPlatform/JP-8.5.2',
        'properties' => [
            'Comment' => 'Access NetFront 3.5',
            'Browser' => 'NetFront',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Access',
            'Browser_Modus' => 'unknown',
            'Version' => '3.5',
            'Platform' => 'JAVA',
            'Platform_Version' => 'unknown',
            'Platform_Description' => 'unknown',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Oracle',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => false,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '2',
            'Device_Name' => 'Elm',
            'Device_Maker' => 'SonyEricsson',
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'unknown',
            'Device_Code_Name' => 'J10i2',
            'Device_Brand_Name' => 'SonyEricsson',
            'RenderingEngine_Name' => 'NetFront',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Access',
        ],
        'lite' => false,
        'standard' => false,
        'full' => true,
    ],
    'issue-1442-B (standard)' => [
        'ua' => 'SonyEricssonJ10i2/R7CA Browser/NetFront/3.5 Profile/MIDP-2.1 Configuration/CLDC-1.1 JavaPlatform/JP-8.5.2',
        'properties' => [
            'Comment' => 'Access NetFront 3.5',
            'Browser' => 'NetFront',
            'Browser_Maker' => 'Access',
            'Version' => '3.5',
            'Platform' => 'unknown',
            'Device_Type' => 'Mobile Device',
            'Device_Pointing_Method' => 'unknown',
        ],
        'lite' => false,
        'standard' => true,
        'full' => false,
    ],
];
