<?php

return [
    'issue-959' => [
        'ua' => 'Mozilla/5.0 (Linux; U; Android 6.0; en-US; XT1068 Build/MPB24.65-34) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/10.8.8.730 U3/0.8.0 Mobile Safari/534.30',
        'properties' => [
            'Comment' => 'UC Browser 10.8',
            'Browser' => 'UC Browser',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'UCWeb Inc.',
            'Browser_Modus' => 'unknown',
            'Version' => '10.8',
            'MajorVer' => '10',
            'MinorVer' => '8',
            'Platform' => 'Android',
            'Platform_Version' => '6.0',
            'Platform_Description' => 'Android OS',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Google Inc',
            'Alpha' => false,
            'Beta' => false,
            'Win16' => false,
            'Win32' => false,
            'Win64' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'BackgroundSounds' => false,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => false,
            'ActiveXControls' => false,
            'isMobileDevice' => true,
            'isTablet' => false,
            'isSyndicationReader' => false,
            'Crawler' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'AolVersion' => '0',
            'Device_Name' => 'Moto G 2nd Gen',
            'Device_Maker' => 'Motorola',
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'XT1068',
            'Device_Brand_Name' => 'Motorola',
            'RenderingEngine_Name' => 'U3',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'UCWeb Inc.',
        ],
        'lite' => false,
        'standard' => true,
    ],
];
