<?php

return [
    'issue-1646-A' => [
        'ua' => 'Athens15_TD/V2 Linux/3.0.13 Android/5.1 andy_5EI3 Release/02.15.2012 Browser/AppleWebKit534.30 Mobile Safari/534.30 System/Android 5.1;',
        'properties' => [
            'Comment' => 'Android Browser 4.0',
            'Browser' => 'Android',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Google Inc',
            'Browser_Modus' => 'unknown',
            'Version' => '4.0',
            'Platform' => 'Android',
            'Platform_Version' => '4.0',
            'Platform_Description' => 'Android OS',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Google Inc',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => true,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'Andy 5EI3',
            'Device_Maker' => 'Yezz',
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'Andy 5EI3',
            'Device_Brand_Name' => 'Yezz',
            'RenderingEngine_Name' => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Apple Inc',
        ],
        'lite' => false,
        'standard' => false,
        'full' => true,
    ],
];
