<?php

return [
    'issue-145' => [
        'ua' => 'Nokia7230/5.0 (05.71) Profile/MIDP-2.1 Configuration/CLDC-1.1 Mozilla/5.0 AppleWebKit/420+ (KHTML, like Gecko) Safari/420+',
        'properties' => [
            'Comment' => 'Nokia Browser',
            'Browser' => 'Nokia Browser',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Nokia',
            'Browser_Modus' => 'unknown',
            'Version' => '0.0',
            'Platform' => 'Series40',
            'Platform_Version' => 'unknown',
            'Platform_Description' => 'Series 40',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Nokia',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => true,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => '7230',
            'Device_Maker' => 'Nokia',
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'unknown',
            'Device_Code_Name' => '7230',
            'Device_Brand_Name' => 'Nokia',
            'RenderingEngine_Name' => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Apple Inc',
        ],
        'lite' => false,
        'standard' => false,
        'full' => true,
    ],
    'issue-145 (standard)' => [
        'ua' => 'Nokia7230/5.0 (05.71) Profile/MIDP-2.1 Configuration/CLDC-1.1 Mozilla/5.0 AppleWebKit/420+ (KHTML, like Gecko) Safari/420+',
        'properties' => [
            'Comment' => 'Nokia Browser',
            'Browser' => 'Nokia Browser',
            'Browser_Maker' => 'Nokia',
            'Version' => '0.0',
            'Platform' => 'JAVA',
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'unknown',
        ],
        'lite' => false,
        'standard' => true,
        'full' => false,
    ],
];
