<?php

return [
    'issue-1064-A' => [
        'ua' => 'NL-Crawler',
        'properties' => [
            'Comment' => 'Search Engines',
            'Browser' => 'Northern Light Web Search',
            'Browser_Type' => 'Bot/Crawler',
            'Browser_Bits' => '0',
            'Browser_Maker' => 'Northern Light',
            'Browser_Modus' => 'unknown',
            'Version' => '0.0',
            'Platform' => 'unknown',
            'Platform_Version' => 'unknown',
            'Platform_Description' => 'unknown',
            'Platform_Bits' => '0',
            'Platform_Maker' => 'unknown',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => false,
            'IFrames' => false,
            'Tables' => false,
            'Cookies' => false,
            'JavaScript' => false,
            'VBScript' => false,
            'JavaApplets' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '0',
            'Device_Name' => 'unknown',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'unknown',
            'Device_Pointing_Method' => 'unknown',
            'Device_Code_Name' => 'unknown',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'unknown',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
    'issue-1064-B' => [
        'ua' => 'Mozilla/5.0 (compatible; NLCrawler/2.0.27; Linux 2.6.3-7; i686; en_US)KHTML/3.4.89 (like Gecko)',
        'properties' => [
            'Comment' => 'Search Engines',
            'Browser' => 'Northern Light Web Search',
            'Browser_Type' => 'Bot/Crawler',
            'Browser_Bits' => '0',
            'Browser_Maker' => 'Northern Light',
            'Browser_Modus' => 'unknown',
            'Version' => '0.0',
            'Platform' => 'unknown',
            'Platform_Version' => 'unknown',
            'Platform_Description' => 'unknown',
            'Platform_Bits' => '0',
            'Platform_Maker' => 'unknown',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => false,
            'IFrames' => false,
            'Tables' => false,
            'Cookies' => false,
            'JavaScript' => false,
            'VBScript' => false,
            'JavaApplets' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '0',
            'Device_Name' => 'unknown',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'unknown',
            'Device_Pointing_Method' => 'unknown',
            'Device_Code_Name' => 'unknown',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'unknown',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
];
