<?php

return [
    'issue-042' => [
        'ua' => 'Mozilla/5.0 (BB10; Kbd) AppleWebKit/537.35+ (KHTML, like Gecko)',
        'properties' => [
            'Comment' => 'BlackBerry 10.0',
            'Browser' => 'BlackBerry',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Research In Motion Limited',
            'Browser_Modus' => 'unknown',
            'Version' => '10.0',
            'Platform' => 'RIM OS',
            'Platform_Version' => '10.0',
            'Platform_Description' => 'RIM OS',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Research In Motion Limited',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => true,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'KBD',
            'Device_Maker' => 'BlackBerry Limited',
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'KBD',
            'Device_Brand_Name' => 'BlackBerry',
            'RenderingEngine_Name' => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Apple Inc',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
];
