<?php

return [
    'issue-1060' => [
        'ua' => 'Mozilla/5.0 (Windows NT 5.1; rv:48.0) Gecko/20100101 Firefox/48.0',
        'properties' => [
            'Comment' => 'Firefox 48.0',
            'Browser' => 'Firefox',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Mozilla Foundation',
            'Browser_Modus' => 'unknown',
            'Version' => '48.0',
            'Platform' => 'WinXP',
            'Platform_Version' => '5.1',
            'Platform_Description' => 'Windows XP',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Microsoft Corporation',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => true,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'Windows Desktop',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
            'Device_Code_Name' => 'Windows Desktop',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'Gecko',
            'RenderingEngine_Version' => '48.0',
            'RenderingEngine_Maker' => 'Mozilla Foundation',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
];
