<?php

return [
    'issue-1306-A' => [
        'ua' => 'Mozilla/5.0 (iPhone; CPU OS 10_2_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) 1Password/6.5.3 (like Version/10.2.1 Mobile/14D27 Safari/600.1.4)',
        'properties' => [
            'Comment' => '1Password 6.5',
            'Browser' => '1Password',
            'Browser_Type' => 'Application',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'AgileBits, Inc.',
            'Browser_Modus' => 'unknown',
            'Version' => '6.5',
            'Platform' => 'iOS',
            'Platform_Version' => '10.2',
            'Platform_Description' => 'iPod, iPhone & iPad',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Apple Inc',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => true,
            'isSyndicationReader' => false,
            'Crawler' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'iPhone',
            'Device_Maker' => 'Apple Inc',
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'iPhone',
            'Device_Brand_Name' => 'Apple',
            'RenderingEngine_Name' => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Apple Inc',
        ],
        'lite' => false,
        'standard' => false,
        'full' => true,
    ],
    'issue-1306-A (standard)' => [
        'ua' => 'Mozilla/5.0 (iPhone; CPU OS 10_2_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) 1Password/6.5.3 (like Version/10.2.1 Mobile/14D27 Safari/600.1.4)',
        'properties' => [
            'Comment' => '1Password 6.5',
            'Browser' => '1Password',
            'Browser_Maker' => 'AgileBits, Inc.',
            'Version' => '6.5',
            'Platform' => 'iOS',
            'Crawler' => false,
            'Device_Type' => 'Mobile Device',
            'Device_Pointing_Method' => 'touchscreen',
        ],
        'lite' => false,
        'standard' => true,
        'full' => false,
    ],
    'issue-1306-A (lite)' => [
        'ua' => 'Mozilla/5.0 (iPhone; CPU OS 10_2_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) 1Password/6.5.3 (like Version/10.2.1 Mobile/14D27 Safari/600.1.4)',
        'properties' => [
            'Comment' => 'Mobile Safari Generic',
            'Browser' => 'Safari',
            'Version' => '0.0',
            'Platform' => 'iOS',
            'Device_Type' => 'Mobile Phone',
        ],
        'lite' => true,
        'standard' => false,
        'full' => false,
    ],
];
