<?php

return [
    'issue-1652' => [
        'ua' => 'Mozilla/5.0 (PlayStation Vita 3.65) AppleWebKit/537.73 (KHTML, like Gecko) Silk/3.2',
        'properties' => [
            'Comment' => 'PlayStation Vita',
            'Browser' => 'Playstation Browser',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '0',
            'Browser_Maker' => 'Sony',
            'Browser_Modus' => 'unknown',
            'Version' => '3.2',
            'Platform' => 'Playstation Vita',
            'Platform_Version' => 'unknown',
            'Platform_Description' => 'Playstation Vita System Software',
            'Platform_Bits' => '0',
            'Platform_Maker' => 'Sony',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => true,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'PlayStation Vita',
            'Device_Maker' => 'Sony',
            'Device_Type' => 'Console',
            'Device_Pointing_Method' => 'unknown',
            'Device_Code_Name' => 'PlayStation Vita',
            'Device_Brand_Name' => 'Sony',
            'RenderingEngine_Name' => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Apple Inc',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
];
