<?php

return [
    'issue-1163' => [
        'ua' => 'Mozilla/5.0 (SMART-TV; Linux; Tizen 2.4.0) AppleWebkit/538.1 (KHTML, like Gecko) SamsungBrowser/1.1 TV Safari/538.1',
        'properties' => [
            'Comment' => 'Samsung Browser 1.1 for TV',
            'Browser' => 'Samsung Browser',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Samsung',
            'Browser_Modus' => 'unknown',
            'Version' => '1.1',
            'MajorVer' => '1',
            'MinorVer' => '1',
            'Platform' => 'Tizen',
            'Platform_Version' => '2.4',
            'Platform_Description' => 'Tizen',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Linux Foundation',
            'Alpha' => false,
            'Beta' => false,
            'Win16' => false,
            'Win32' => false,
            'Win64' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'BackgroundSounds' => false,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => true,
            'ActiveXControls' => false,
            'isMobileDevice' => false,
            'isTablet' => false,
            'isSyndicationReader' => false,
            'Crawler' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'AolVersion' => '0',
            'Device_Name' => 'Smart TV',
            'Device_Maker' => 'Samsung',
            'Device_Type' => 'TV Device',
            'Device_Pointing_Method' => 'unknown',
            'Device_Code_Name' => 'Smart TV',
            'Device_Brand_Name' => 'Samsung',
            'RenderingEngine_Name' => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Apple Inc',
        ],
        'lite' => false,
        'standard' => true,
    ],
];
