<?php

return [
    'issue-1102' => [
        'ua' => 'Mozilla/5.0 (Windows NT 6.2; WOW64; rv:7.0.1) Gecko/20151105 Postbox/4.0.8',
        'properties' => [
            'Comment' => 'Postbox 4.0',
            'Browser' => 'Postbox',
            'Browser_Type' => 'Email Client',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Postbox, Inc.',
            'Browser_Modus' => 'unknown',
            'Version' => '4.0',
            'Platform' => 'Win8',
            'Platform_Version' => '6.2',
            'Platform_Description' => 'Windows 8',
            'Platform_Bits' => '64',
            'Platform_Maker' => 'Microsoft Corporation',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => true,
            'isSyndicationReader' => false,
            'Crawler' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '2',
            'Device_Name' => 'Windows Desktop',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
            'Device_Code_Name' => 'Windows Desktop',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'Gecko',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Mozilla Foundation',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
];
