<?php
declare(strict_types = 1);

return [
    'issue-2530-A' => [
        'ua' => 'Dalvik/2.1.0 (Linux; U; Android 10; SM-G960N Build/QP1A.190711.020)',
        'properties' => [
            'Comment' => 'Dalvik 2.1',
            'Browser' => 'Dalvik',
            'Browser_Type' => 'Application',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Google Inc',
            'Browser_Modus' => 'unknown',
            'Version' => '2.1',
            'Platform' => 'Android',
            'Platform_Version' => '10.0',
            'Platform_Description' => 'Android OS',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Google Inc',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => true,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'Galaxy S9',
            'Device_Maker' => 'Samsung',
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'SM-G960N',
            'Device_Brand_Name' => 'Samsung',
            'RenderingEngine_Name' => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Apple Inc',
        ],
        'lite' => false,
        'standard' => false,
        'full' => true,
    ],
];
