<?php

return [
    'issue-032' => [
        'ua' => 'Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; MASMJS; rv:11.0) like Gecko',
        'properties' => [
            'Comment' => 'IE 11.0',
            'Browser' => 'IE',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Microsoft Corporation',
            'Browser_Modus' => 'unknown',
            'Version' => '11.0',
            'MajorVer' => '11',
            'MinorVer' => '0',
            'Platform' => 'Win8.1',
            'Platform_Version' => '6.3',
            'Platform_Description' => 'Windows 8.1',
            'Platform_Bits' => '64',
            'Platform_Maker' => 'Microsoft Corporation',
            'Alpha' => false,
            'Beta' => false,
            'Win16' => false,
            'Win32' => false,
            'Win64' => true,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'BackgroundSounds' => true,
            'JavaScript' => true,
            'VBScript' => true,
            'JavaApplets' => true,
            'ActiveXControls' => true,
            'isMobileDevice' => false,
            'isTablet' => false,
            'isSyndicationReader' => false,
            'Crawler' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'AolVersion' => '0',
            'Device_Name' => 'Windows Desktop',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
            'Device_Code_Name' => 'Windows Desktop',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'Trident',
            'RenderingEngine_Version' => '7.0',
            'RenderingEngine_Maker' => 'Microsoft Corporation',
        ],
        'lite' => true,
        'standard' => true,
    ],
];
