<?php

declare(strict_types=1);

return [
    'issue-578-A' => [
        'ua' => 'check_http/v1.4.16 (nagios-plugins 1.4.16)',
        'properties' => [
            'Comment' => 'Nagios',
            'Browser' => 'Nagios',
            'Browser_Type' => 'Bot/Crawler',
            'Browser_Bits' => '0',
            'Browser_Maker' => 'Nagios Enterprises, LLC.',
            'Browser_Modus' => 'unknown',
            'Version' => '1.4',
            'Platform' => 'unknown',
            'Platform_Version' => 'unknown',
            'Platform_Description' => 'unknown',
            'Platform_Bits' => '0',
            'Platform_Maker' => 'unknown',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => false,
            'IFrames' => false,
            'Tables' => false,
            'Cookies' => false,
            'JavaScript' => false,
            'VBScript' => false,
            'JavaApplets' => false,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '0',
            'Device_Name' => 'unknown',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'unknown',
            'Device_Pointing_Method' => 'unknown',
            'Device_Code_Name' => 'unknown',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'unknown',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
    'issue-578-B' => [
        'ua' => 'check_http/v2.0 (nagios-plugins 2.0)',
        'properties' => [
            'Comment' => 'Nagios',
            'Browser' => 'Nagios',
            'Browser_Type' => 'Bot/Crawler',
            'Browser_Bits' => '0',
            'Browser_Maker' => 'Nagios Enterprises, LLC.',
            'Browser_Modus' => 'unknown',
            'Version' => '2.0',
            'Platform' => 'unknown',
            'Platform_Version' => 'unknown',
            'Platform_Description' => 'unknown',
            'Platform_Bits' => '0',
            'Platform_Maker' => 'unknown',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => false,
            'IFrames' => false,
            'Tables' => false,
            'Cookies' => false,
            'JavaScript' => false,
            'VBScript' => false,
            'JavaApplets' => false,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '0',
            'Device_Name' => 'unknown',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'unknown',
            'Device_Pointing_Method' => 'unknown',
            'Device_Code_Name' => 'unknown',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'unknown',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
];
