<?php

return [
    'issue-1236-A' => [
        'ua' => 'Mozilla/5.0 (New Nintendo 3DS like iPhone) AppleWebKit/536.30 (KHTML, like Gecko) NX/3.0.0.5.20 Mobile NintendoBrowser/1.8.10156.US',
        'properties' => [
            'Comment' => 'Nintendo Browser 1.8',
            'Browser' => 'Nintendo Browser',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Nintendo',
            'Browser_Modus' => 'unknown',
            'Version' => '1.8',
            'Platform' => 'Nintendo 3DS',
            'Platform_Version' => 'unknown',
            'Platform_Description' => 'Nintendo 3DS/New Nintendo 3DS System Software',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Nintendo',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => false,
            'isMobileDevice' => true,
            'isTablet' => false,
            'isSyndicationReader' => false,
            'Crawler' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'New 3DS',
            'Device_Maker' => 'Nintendo',
            'Device_Type' => 'Console',
            'Device_Pointing_Method' => 'stylus',
            'Device_Code_Name' => 'New 3DS',
            'Device_Brand_Name' => 'Nintendo',
            'RenderingEngine_Name' => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Apple Inc',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
];
