<?php

return [
    'issue-826-A' => [
        'ua' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5 (Applebot/0.1; +http://www.apple.com/go/applebot)',
        'properties' => [
            'Comment' => 'Applebot 0.1',
            'Browser' => 'Applebot',
            'Browser_Type' => 'Bot/Crawler',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Apple Inc',
            'Browser_Modus' => 'unknown',
            'Version' => '0.1',
            'Platform' => 'MacOSX',
            'Platform_Version' => '10',
            'Platform_Description' => 'Mac OS X',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Apple Inc',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => true,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'Macintosh',
            'Device_Maker' => 'Apple Inc',
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
            'Device_Code_Name' => 'Macintosh',
            'Device_Brand_Name' => 'Apple',
            'RenderingEngine_Name' => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Apple Inc',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
    'issue-826-B' => [
        'ua' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5 (Applebot/0.1)',
        'properties' => [
            'Comment' => 'Applebot 0.1',
            'Browser' => 'Applebot',
            'Browser_Type' => 'Bot/Crawler',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Apple Inc',
            'Browser_Modus' => 'unknown',
            'Version' => '0.1',
            'Platform' => 'MacOSX',
            'Platform_Version' => '10',
            'Platform_Description' => 'Mac OS X',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Apple Inc',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => true,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'Macintosh',
            'Device_Maker' => 'Apple Inc',
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
            'Device_Code_Name' => 'Macintosh',
            'Device_Brand_Name' => 'Apple',
            'RenderingEngine_Name' => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Apple Inc',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
];
