<?php

return [
    'issue-1117' => [
        'ua' => 'MacOutlook/15.27.0.161010 (Intelx64 Mac OS X Version 10.11.6 (Build 15G1108))',
        'properties' => [
            'Comment' => 'Microsoft Outlook 2013',
            'Browser' => 'Outlook',
            'Browser_Type' => 'Email Client',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Microsoft Corporation',
            'Browser_Modus' => 'unknown',
            'Version' => '2013',
            'MajorVer' => '2013',
            'MinorVer' => '0',
            'Platform' => 'MacOSX',
            'Platform_Version' => '10',
            'Platform_Description' => 'Mac OS X',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Apple Inc',
            'Alpha' => false,
            'Beta' => false,
            'Win16' => false,
            'Win32' => false,
            'Win64' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'BackgroundSounds' => true,
            'JavaScript' => false,
            'VBScript' => true,
            'JavaApplets' => true,
            'ActiveXControls' => true,
            'isMobileDevice' => false,
            'isTablet' => false,
            'isSyndicationReader' => false,
            'Crawler' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '2',
            'AolVersion' => '0',
            'Device_Name' => 'Macintosh',
            'Device_Maker' => 'Apple Inc',
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
            'Device_Code_Name' => 'Macintosh',
            'Device_Brand_Name' => 'Apple',
            'RenderingEngine_Name' => 'Trident',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Microsoft Corporation',
        ],
        'lite' => true,
        'standard' => false,
    ],
];
