<?php

return [
    'issue-164' => [
        'ua' => 'Mozilla/4.0 (compatible; MSIE 10.0; Trident/6.0; Windows 98; MyIE2)',
        'properties' => [
            'Comment' => 'Maxthon 2.0',
            'Browser' => 'Maxthon',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Maxthon International Limited',
            'Browser_Modus' => 'unknown',
            'Version' => '2.0',
            'Platform' => 'Win98',
            'Platform_Version' => '98',
            'Platform_Description' => 'Windows 98',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Microsoft Corporation',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => true,
            'JavaApplets' => true,
            'isSyndicationReader' => false,
            'Crawler' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '2',
            'Device_Name' => 'Windows Desktop',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
            'Device_Code_Name' => 'Windows Desktop',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'Trident',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Microsoft Corporation',
        ],
        'lite' => false,
        'standard' => false,
        'full' => true,
    ],
    'issue-164 (standard)' => [
        'ua' => 'Mozilla/4.0 (compatible; MSIE 10.0; Trident/6.0; Windows 98; MyIE2)',
        'properties' => [
            'Comment' => 'Maxthon 2.0',
            'Browser' => 'Maxthon',
            'Browser_Maker' => 'Maxthon International Limited',
            'Version' => '2.0',
            'Platform' => 'Win32',
            'Crawler' => false,
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
        ],
        'lite' => false,
        'standard' => true,
        'full' => false,
    ],
    'issue-164 (lite)' => [
        'ua' => 'Mozilla/4.0 (compatible; MSIE 10.0; Trident/6.0; Windows 98; MyIE2)',
        'properties' => [
            'Comment' => 'IE 10.0',
            'Browser' => 'IE',
            'Version' => '10.0',
            'Platform' => 'Win32',
            'Device_Type' => 'Desktop',
        ],
        'lite' => true,
        'standard' => false,
        'full' => false,
    ],
];
