<?php

declare(strict_types=1);

return [
    'issue-1717-A' => [
        'ua' => 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2110.0 TeslaBrowser/1.0.0.4863 Safari/537.36',
        'properties' => [
            'Comment' => 'TeslaBrowser',
            'Browser' => 'TeslaBrowser',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'RostPay Ltd',
            'Browser_Modus' => 'unknown',
            'Version' => '0.0',
            'Platform' => 'Win8.1',
            'Platform_Version' => '6.3',
            'Platform_Description' => 'Windows 8.1',
            'Platform_Bits' => '64',
            'Platform_Maker' => 'Microsoft Corporation',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => false,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'Windows Desktop',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
            'Device_Code_Name' => 'Windows Desktop',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Google Inc',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
];
