<?php

declare(strict_types=1);

return [
    'issue-1825-A' => [
        'ua' => 'Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.2.1 Chrome/38.0.2125.122 Safari/537.36 WebAppManager',
        'properties' => [
            'Comment' => 'QtWebEngine 5.2 for TV',
            'Browser' => 'QtWebEngine',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'unknown',
            'Browser_Modus' => 'unknown',
            'Version' => '5.2',
            'Platform' => 'webOS',
            'Platform_Version' => '3.0',
            'Platform_Description' => 'LG webOS',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'LG',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => false,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'TV',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'TV Device',
            'Device_Pointing_Method' => 'unknown',
            'Device_Code_Name' => 'TV',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Google Inc',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
];
