<?php

return [
    'issue-2031-A' => [
        'ua' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/61.0.3163.100 Chrome/61.0.3163.100 Safari/537.36 PingdomPageSpeed/1.0 (pingbot/2.0; +http://www.pingdom.com/)',
        'properties' => [
            'Comment' => 'Pingdom Pagespeed',
            'Browser' => 'Pingdom Transaction Monitoring',
            'Browser_Type' => 'Bot/Crawler',
            'Browser_Bits' => '64',
            'Browser_Maker' => 'Pingdom AB.',
            'Browser_Modus' => 'unknown',
            'Version' => '0.0',
            'Platform' => 'Ubuntu',
            'Platform_Version' => 'unknown',
            'Platform_Description' => 'Ubuntu Linux',
            'Platform_Bits' => '64',
            'Platform_Maker' => 'Canonical Foundation',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => false,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'Linux Desktop',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
            'Device_Code_Name' => 'Linux Desktop',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Google Inc',
        ],
        'lite' => false,
        'standard' => false,
        'full' => true,
    ],
];
