<?php

return [
    'issue-1642' => [
        'ua' => 'Mozilla/5.0 (X11; SunOS i86pc; rv:52.0) Gecko/20100101 Thunderbird/52.3.0',
        'properties' => [
            'Comment' => 'Thunderbird 52.3',
            'Browser' => 'Thunderbird',
            'Browser_Type' => 'Email Client',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Mozilla Foundation',
            'Browser_Modus' => 'unknown',
            'Version' => '52.3',
            'Platform' => 'SunOS',
            'Platform_Version' => 'unknown',
            'Platform_Description' => 'SunOS',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Oracle',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => true,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'general Desktop',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
            'Device_Code_Name' => 'general Desktop',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'Gecko',
            'RenderingEngine_Version' => '52.0',
            'RenderingEngine_Maker' => 'Mozilla Foundation',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
];
