<?php

return [
    'issue-1119' => [
        'ua' => 'Kurio/3.1.9 Build 66400(Android Kitkat 4.4.4; Phone)',
        'properties' => [
            'Comment' => 'Kurio App',
            'Browser' => 'Kurio App',
            'Browser_Type' => 'Application',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'CIDE Interactive',
            'Browser_Modus' => 'unknown',
            'Version' => '3.1',
            'Platform' => 'Android',
            'Platform_Version' => 'unknown',
            'Platform_Description' => 'Android OS',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Google Inc',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => false,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'general Mobile Phone',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'general Mobile Phone',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Google Inc',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
];
