<?php

declare(strict_types=1);

return [
    'issue-1070' => [
        'ua' => 'Mozilla/5.0 (Windows NT 6.3; ARM; Trident/7.0;Touch;rv: 11.0) like Gecko',
        'properties' => [
            'Comment' => 'IE 11.0',
            'Browser' => 'IE',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Microsoft Corporation',
            'Browser_Modus' => 'unknown',
            'Version' => '11.0',
            'Platform' => 'WinRT8.1',
            'Platform_Version' => '6.3',
            'Platform_Description' => 'Windows RT 8.1',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Microsoft Corporation',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => true,
            'JavaApplets' => true,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'general Tablet',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'Tablet',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'general Tablet',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'Trident',
            'RenderingEngine_Version' => '7.0',
            'RenderingEngine_Maker' => 'Microsoft Corporation',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
    'issue-1070 (lite)' => [
        'ua' => 'Mozilla/5.0 (Windows NT 6.3; ARM; Trident/7.0;Touch;rv: 11.0) like Gecko',
        'properties' => [
            'Comment' => 'IE 11.0',
            'Browser' => 'IE',
            'Version' => '11.0',
            'Platform' => 'Win8.1',
            'Device_Type' => 'Desktop',
        ],
        'lite' => true,
        'standard' => false,
        'full' => false,
    ],
];
