<?php

declare(strict_types=1);

return [
    'issue-1277-A' => [
        'ua' => 'Mozilla/5.0 (compatible; Yeti/1.1; +http://help.naver.com/support/robots.html)',
        'properties' => [
            'Comment' => 'NaverBot',
            'Browser' => 'NaverBot',
            'Browser_Type' => 'Bot',
            'Browser_Bits' => '0',
            'Browser_Maker' => 'NHN Corporation',
            'Browser_Modus' => 'unknown',
            'Version' => '1.1',
            'Platform' => 'unknown',
            'Platform_Version' => 'unknown',
            'Platform_Description' => 'unknown',
            'Platform_Bits' => '0',
            'Platform_Maker' => 'unknown',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => false,
            'IFrames' => false,
            'Tables' => false,
            'Cookies' => false,
            'JavaScript' => false,
            'VBScript' => false,
            'JavaApplets' => false,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '0',
            'Device_Name' => 'unknown',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'unknown',
            'Device_Pointing_Method' => 'unknown',
            'Device_Code_Name' => 'unknown',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'unknown',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
    'issue-1277-B' => [
        'ua' => 'Mozilla/5.0 (compatible; Yeti/1.1; +http://naver.me/bot)',
        'properties' => [
            'Comment' => 'NaverBot',
            'Browser' => 'NaverBot',
            'Browser_Type' => 'Bot',
            'Browser_Bits' => '0',
            'Browser_Maker' => 'NHN Corporation',
            'Browser_Modus' => 'unknown',
            'Version' => '1.1',
            'Platform' => 'unknown',
            'Platform_Version' => 'unknown',
            'Platform_Description' => 'unknown',
            'Platform_Bits' => '0',
            'Platform_Maker' => 'unknown',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => false,
            'IFrames' => false,
            'Tables' => false,
            'Cookies' => false,
            'JavaScript' => false,
            'VBScript' => false,
            'JavaApplets' => false,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '0',
            'Device_Name' => 'unknown',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'unknown',
            'Device_Pointing_Method' => 'unknown',
            'Device_Code_Name' => 'unknown',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'unknown',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
];
