<?php

return [
    'issue-2001-A' => [
        'ua' => 'Acast/1.25.2 (Phone; Android 8.0.2; OnePlus 5.0)',
        'properties' => [
            'Comment' => 'Acast Podcast App',
            'Browser' => 'Acast Podcast App',
            'Browser_Type' => 'Multimedia Player',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'Acast AB',
            'Browser_Modus' => 'unknown',
            'Version' => '0.0',
            'Platform' => 'Android',
            'Platform_Version' => '8.0',
            'Platform_Description' => 'Android OS',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Google Inc',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => false,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => '5',
            'Device_Maker' => 'OnePlus',
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'A5000',
            'Device_Brand_Name' => 'OnePlus',
            'RenderingEngine_Name' => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Google Inc',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
    'issue-2001-B' => [
        'ua' => 'Acast/1.46.0 (CarPlay; iOS 12.0.0, iPhone10,3)',
        'properties' => [
            'Comment' => 'Acast Podcast App',
            'Browser' => 'Acast Podcast App',
            'Browser_Type' => 'Multimedia Player',
            'Browser_Bits' => '64',
            'Browser_Maker' => 'Acast AB',
            'Browser_Modus' => 'unknown',
            'Version' => '0.0',
            'Platform' => 'iOS',
            'Platform_Version' => '12.0',
            'Platform_Description' => 'iPod, iPhone & iPad',
            'Platform_Bits' => '64',
            'Platform_Maker' => 'Apple Inc',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => true,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'iPhone',
            'Device_Maker' => 'Apple Inc',
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'iPhone',
            'Device_Brand_Name' => 'Apple',
            'RenderingEngine_Name' => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Apple Inc',
        ],
        'lite' => false,
        'standard' => false,
        'full' => true,
    ],
    'issue-2001-B (standard)' => [
        'ua' => 'Acast/1.46.0 (CarPlay; iOS 12.0.0, iPhone10,3)',
        'properties' => [
            'Comment' => 'Acast Podcast App',
            'Browser' => 'Acast Podcast App',
            'Browser_Maker' => 'Acast AB',
            'Version' => '0.0',
            'Platform' => 'iOS',
            'Device_Type' => 'Mobile Device',
            'Device_Pointing_Method' => 'touchscreen',
        ],
        'lite' => false,
        'standard' => true,
        'full' => false,
    ],
];
