<?php

return [
    'issue-568' => [
        'ua' => 'Mozilla/5.0 (Linux; U; Android 4.4.2; en-US; SM-T531 Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/10.2.0.535 U3/0.8.0 Mobile Safari/534.30',
        'properties' => [
            'Comment' => 'UC Browser 10.2 for Android',
            'Browser' => 'UC Browser',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '32',
            'Browser_Maker' => 'UCWeb Inc.',
            'Browser_Modus' => 'unknown',
            'Version' => '10.2',
            'Platform' => 'Android',
            'Platform_Version' => '4.4',
            'Platform_Description' => 'Android OS',
            'Platform_Bits' => '32',
            'Platform_Maker' => 'Google Inc',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => false,
            'isSyndicationReader' => false,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'Galaxy Tab 4 10.1',
            'Device_Maker' => 'Samsung',
            'Device_Type' => 'Tablet',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'SM-T531',
            'Device_Brand_Name' => 'Samsung',
            'RenderingEngine_Name' => 'U3',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'UCWeb Inc.',
        ],
        'lite' => false,
        'standard' => true,
        'full' => true,
    ],
];
