<?php

return [
    'issue-052' => [
        'ua' => 'Mozilla/5.0 (Windows NT; Win64; x64; rv:26.0) Gecko/20100101 Firefox/26.0 Waterfox/26.0',
        'properties' => [
            'Comment' => 'Waterfox 26.0',
            'Browser' => 'Waterfox',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => '64',
            'Browser_Maker' => 'www.waterfoxproject.org',
            'Browser_Modus' => 'unknown',
            'Version' => '26.0',
            'Platform' => 'WinNT',
            'Platform_Version' => 'unknown',
            'Platform_Description' => 'Windows NT',
            'Platform_Bits' => '64',
            'Platform_Maker' => 'Microsoft Corporation',
            'Alpha' => false,
            'Beta' => false,
            'Frames' => true,
            'IFrames' => true,
            'Tables' => true,
            'Cookies' => true,
            'JavaScript' => true,
            'VBScript' => false,
            'JavaApplets' => true,
            'isFake' => false,
            'isAnonymized' => false,
            'isModified' => false,
            'CssVersion' => '3',
            'Device_Name' => 'Windows Desktop',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
            'Device_Code_Name' => 'Windows Desktop',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'Gecko',
            'RenderingEngine_Version' => '26.0',
            'RenderingEngine_Maker' => 'Mozilla Foundation',
        ],
        'lite' => false,
        'standard' => false,
        'full' => true,
    ],
    'issue-052 (standard)' => [
        'ua' => 'Mozilla/5.0 (Windows NT; Win64; x64; rv:26.0) Gecko/20100101 Firefox/26.0 Waterfox/26.0',
        'properties' => [
            'Comment' => 'Waterfox 26.0',
            'Browser' => 'Waterfox',
            'Browser_Maker' => 'www.waterfoxproject.org',
            'Version' => '26.0',
            'Platform' => 'Win32',
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
        ],
        'lite' => false,
        'standard' => true,
        'full' => false,
    ],
];
